<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<NoWarn>$(NoWarn);NU1903</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ShopVerseECommercePlatform.Application\ShopVerseECommercePlatform.Application.csproj" />
		<ProjectReference Include="..\ShopVerseECommercePlatform.Infrastructure\ShopVerseECommercePlatform.Infrastructure.csproj" />
		<ProjectReference Include="..\ShopVerseECommercePlatform.Persistence\ShopVerseECommercePlatform.Persistence.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\Files\" />
	</ItemGroup>

</Project>
